// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWkGKpy1Xr4eqSidJ3tYYVKGrIX4ssabE',
    appId: '1:690474442853:web:263d86a8ccd26ace61e68c',
    messagingSenderId: '690474442853',
    projectId: 'foodfiesta-414305',
    authDomain: 'foodfiesta-414305.firebaseapp.com',
    storageBucket: 'foodfiesta-414305.appspot.com',
    measurementId: 'G-ZGBTF5E3J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwGl1ObjStP9Ybir0g6lQELEB5nBHZNc',
    appId: '1:690474442853:android:a9d0fd413939570761e68c',
    messagingSenderId: '690474442853',
    projectId: 'foodfiesta-414305',
    storageBucket: 'foodfiesta-414305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwhVRq4T0oyHgzxsn3r88ChcaunST0ik',
    appId: '1:690474442853:ios:1ee98445d14923ae61e68c',
    messagingSenderId: '690474442853',
    projectId: 'foodfiesta-414305',
    storageBucket: 'foodfiesta-414305.appspot.com',
    iosBundleId: 'com.example.foodapplication',
  );
}
